Transactions refactored + other fixes
bretpeters3n/seal-team-3 pull request #121
Opened 2022-03-21 23:10 UTC by bycho91

- Get all transactions method is no longer used. All the data being pulled from getBudgetByID is what is being used for transactions.

2022-03-21 23:52 UTC, Jmartimus requested changes

2022-03-21 23:52 UTC, Jmartimus commented on client/src/components/TransactionItem/TransactionItem.tsx
> +    // toggleRerender();
Do you need this?

2022-03-21 23:52 UTC, Jmartimus commented on client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
> +    // toggleRerender();
And this?

2022-03-21 23:57 UTC, bycho91 commented on client/src/components/TransactionItem/TransactionItem.tsx
> +    // toggleRerender();
nope

2022-03-21 23:57 UTC, bycho91 commented on client/src/components/TransactionItemAdder/TransactionItemAdder.tsx
> +    // toggleRerender();
nope

2022-03-22 00:01 UTC, Jmartimus approved these changes

2022-03-22 00:01 UTC, merged